### PR TITLE
Russian translation.

### PR DESCRIPTION
**Pull request by Dither**
License information (for GPLv3 license).

### CODE REVIEW

**Comment by milchchan** [comment]
Thank you for your Pull Request and Russian translation.
I want to just accept Russian translation. Because I want to investigate and choose a license in the future.

**Comment by Dither** [comment]
Sure. :) I just randomly picked license that seemed closest to the distribution terms of the FAQ to fill the blanks in the Readme.

**Comment by milchchan** [comment]
OK. I will commit a license when I decided a license.
Could you remove GPL license and README.md files from this commit?

**Comment by Dither** [comment]
Done.

I am also interested in translation of `Words.xml` and messages in CHARML-files but can't accommodate the lack of any sort of translatability. While for the `Words.xml` it's probably possible to simply add new translated terms with new translated attributes, for CHARML there is a need for  `lang` attribute (like `<message lang="en" speed="50" duration="00:00:01">Test!</message>`) to distinguish between messages intended for different languages. Can you implement that?

The long strings are better to be translated professionally or with crowd-sourcing though (it might be worthwhile to publish them to http://translatedby.com/ or https://crowdin.com/ or the like).

**Comment by milchchan** [comment]
Thank you! I merged your Pull Request.

I understand your opinion for CHARML-based character files.
But your opinion is not acceptable about `lang` attribute. Sorry!
Basically you create a CHARML-based character file in each language. It's by design.
Because messages can not translate one by one and need to prepare customized characters included modified images in consideration of each culture.
It's my experiences at porting for iOS and other platforms.

**Comment by Dither** [comment]
I understand. Then new characters it is. :)

**Pull request merged**
